VBcomTaskServerBundle_user:
    resource: "@VBcomTaskServerBundle/Resources/config/routing/user.yml"
    prefix:   /server/user

VBcomTaskServerBundle_task:
    resource: "@VBcomTaskServerBundle/Resources/config/routing/task.yml"
    prefix:   /server/task
    
VBcomTaskServerBundle_task_json:
    resource: "@VBcomTaskServerBundle/Resources/config/routing/task_json.yml"
    prefix:   /api/v1/json/task